### ISSUE TITLE
Sex-disaggregation for multiple countries selected

### ISSUE THREAD

**Issue by shfcuppone** [UNICEFECAR/dash#120]
When multiple countries are selected and indicators are disaggregated by sex, some graphs appear overlapping. It is not clear if the lines are "mixed up" or if it's because the colors are all the same. 
The attached photo is of Participation, Eastern European countries only, Out-of-school rate for youth of upper secondary school age (quadrant I), disaggregated by sex.
![TM capture_1](https://user-images.githubusercontent.com/88044470/143223352-6c60dc0a-ce9d-4b2e-9ec5-26a23e9222dc.JPG)

**Comment by jamescw** [comment]
This has been solved a while ago in the latest release: http://tm-dash-dev.azurewebsites.net/child-education

Closing this one
