### ISSUE TITLE
Same color used for multiple countries

### ISSUE THREAD

**Issue by shfcuppone** [UNICEFECAR/dash#121]
Colors are not differentiated in graph, so you cannot tell which data points are for which country in some cases. The attached example is from participation, Eastern European countries only, Out-of-school rate for youth of upper secondary school age (quadrant I), Total.

![TM capture_2](https://user-images.githubusercontent.com/88044470/143225324-b9ab0c14-13f5-4275-8b9a-f58a369f62a1.JPG)

**Comment by jamescw** [comment]
@lbassil lets change the color palette so we have more colours available

**Comment by jamescw** [comment]
This was also solved in the latest version: http://tm-dash-dev.azurewebsites.net/child-education
