### ISSUE TITLE
Data available but displaying as "no data available" 

### ISSUE THREAD

**Issue by shfcuppone** [UNICEFECAR/dash#122]
Some indicators show disaggregated but no overall data. This seems inaccurate, but could we please check if it's an issue with the data or with the graph?

The attached image is from: Learning quality, Ukraine selected, Quadrant I, indicator= percentage of children (aged 36-59 months) developmentally on track in at least 3 of the 4 following domains: literacy-numeracy, physical, social-emotional, and learning. The overall data only shows when "exclude outliers" is toggled off, but if there is only 1 country selected, and the latest data point = 2012, why is it considered an outlier?
![TM capture_5](https://user-images.githubusercontent.com/88044470/143230357-c74efc66-782c-43bc-8817-00a70b6346d4.JPG)
![TM capture_4](https://user-images.githubusercontent.com/88044470/143230362-12a6a859-9efc-4c9e-8221-2e60b22e7a51.JPG)
![TM capture_3](https://user-images.githubusercontent.com/88044470/143230363-89216362-5a92-47e6-80a8-ce8bad0f5965.JPG)

**Comment by lbassil** [comment]
This has been fixed. It is not that the one value was considered as an outlier, but the way the zscore works when we have only one data points or all the points have similar value... so we had to fine tune this to work.
