### ISSUE TITLE
Round to whole numbers for graphs

### ISSUE THREAD

**Issue by jamescw** [UNICEFECAR/dash#148]
Discuss with Deepak what the rounding rules should be

**Comment by jamescw** [comment]
We may need a sensible default (maybe 2 decimal places) with an override per indicator or by unit type (percentage etc).

**Comment by beto-Sibileau** [comment]
Based on last call, Nahid suggested:
- whole numbers round unless values are less than one, then round to one decimal
- if unit is index, then round to two decimals

@jamescw do you suggest to include this right after the data query call? Then, it should affect all the flow downstream
