### ISSUE TITLE
Remove old indicators from the dashboard

### ISSUE THREAD

**Issue by jamescw** [UNICEFECAR/dash#151]

**Comment by lbassil** [comment]
Hi @jamescw , how can I know what indicators need to be removed? Do we have a list of that or I should talk to Deepak?

**Comment by lbassil** [comment]
Ok good, thanks!

**Comment by beto-Sibileau** [comment]
Your welcome @lbassil ! First task is done, and is related to the update of the indicator config for new indicators. Next step is to erase old indicators, that part is easy and I'll retake it on tuesday. In the meantime, I requested Deepak his input about new indicators for children withouth parental care and Justice for Children, this may eventually derive in the addition of new areas (which I understand should be easy, just by adding them in the config with proper dictionary key/values related)
