### ISSUE TITLE
OVERLAP: country legend on line plots

### ISSUE THREAD

**Issue by beto-Sibileau** [UNICEFECAR/dash#155]
- Shown below for 5 countries: ![image](https://user-images.githubusercontent.com/62593695/165501306-cbe3f39f-070f-44d1-979e-e73bf8946893.png)
- Naturally gets worse when all countries selected

Should we try a smaller `fontsize` or any other ideas @lbassil and @jamescw on this?

**Comment by jamescw** [comment]
You mean the legend is overlapping the line plot?

**Comment by beto-Sibileau** [comment]
> You mean the legend is overlapping the line plot?

Exactly, and I think when more countries are added, it may also overlapp the x-axis (eg: 2020 below).
- I also realized it will be good to order alphabetically the country list in the legend !!! (see below): 
![image](https://user-images.githubusercontent.com/62593695/165530152-886a4c0d-57af-4de9-bea1-f0ca65ab7ee8.png)
