### ISSUE TITLE
Add the ability to have a title for each area so that it is clear what the indicators are related to

### ISSUE THREAD

**Issue by jamescw** [UNICEFECAR/dash#19]

**Comment by jamescw** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/440684/125940128-5cc7c4e0-44e9-4e57-ac97-b4f831015bf0.png)

**Comment by shfcuppone** [comment]
Participation:
- Area 1 (map): Out-of-school children
- Area 2 & 3 (across both): Education entry and transition
- Area 4: Safe and inclusive learning environments
- Area 5: Education completion (see other issue raised on moving a few of these indicators)

Learning quality
- Area 1 (map): What students know and can do
- Area 2 & 3 (across both): Foundational skills
- Area 4 & 5 (across both): Trained and qualified teachers

Governance
- Area 1: Guaranteeing and paying for education**
- Areas 2 & 3 (across both): Public and private enrolments
- Area 4: Government education expenditure
- Area 5: Administration of learning assessments

**Need to ask colleagues on this one. The combination of indicators makes it difficult.

**Comment by jamescw** [comment]
Docs:
https://dash-bootstrap-components.opensource.faculty.ai/docs/components/card/

Styles:
https://seotest.buzz/dash/#
