### ISSUE TITLE
Indicators under the Governance sub-topic of Education

### ISSUE THREAD

**Issue by lbassil** [UNICEFECAR/dash#21]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/86417315/126047883-41a76166-7d5e-4b66-a9dc-32c7fe9c4605.png)
What is the plan to do with the indicators under the Governance sub-topic of Education that are not being displayed in area 4 because the OBS VALUE is boolean (0 or 1)?

Not sure if the solution is to have a pie chart showing the percentages of the yes and the no, and upon hovering the tooltip is the list of countries belonging to the yes or no categories.... do u think this is a good idea and feasible idea?

**Comment by beto-Sibileau** [comment]
hi @lbassil I'll revise the PR you linked to this one, thanks!
