### ISSUE TITLE
Calculate card based on time range for some cards

### ISSUE THREAD

**Issue by jamescw** [UNICEFECAR/dash#33]

**Comment by lbassil** [comment]
I tried to work on this as part of my trials, and if it is just to show [min,max] when specified on the card, I can do it myself, straightforward.

**Comment by lbassil** [comment]
![image](https://user-images.githubusercontent.com/86417315/128484442-ef8cbc93-60bf-4d13-947a-aba787446287.png)
This is a sample how it can look... 

I added a "min_max" flag to the card and another "average" flag to use where applicable. I guess this will improve the numbers on the cards.
