### ISSUE TITLE
add profiler to vs-code for performance

### ISSUE THREAD

**Issue by beto-Sibileau** [UNICEFECAR/dash#48]

**Comment by beto-Sibileau** [comment]
As a total docker ignorant:
- could we try docker / non docker comparisson?
- Is it possible that docker don't use the full power of the server? 
- Could we assign more power/resources to docker on the server?

**Comment by jamescw** [comment]
The issue is due to cache chuck size, some code optimization do to for repetitive calcualtions that need to be cached
