### ISSUE TITLE
Geocode based on country ISO codes

### ISSUE THREAD

**Issue by beto-Sibileau** [UNICEFECAR/dash#7]
### avoid missed locations based on country names

- check Plotly geocode
- check Kosovo for Eurostat indicators

**Comment by lbassil** [comment]
Hello James and Alberto,

Can you we quickly discuss this bug to know exactly what is the problem and what needs to be done?

Thanks.

**Comment by beto-Sibileau** [comment]
> Hello James and Alberto,
> 
> Can you we quickly discuss this bug to know exactly what is the problem and what needs to be done?
> 
> Thanks.

Indeed @lbassil, great initiative! @jamescw could you suggest any suitable time for you please?

**Comment by beto-Sibileau** [comment]
sorry @jamescw about this, should we try to explore this one to release you?

**Comment by lbassil** [comment]
Hi @beto-Sibileau , so why do we need to do this? Is it separate from the other task/issues assigned to me in order to make sure we solve the filter by country name following the SDMX naming?

Is this more related to the map?

**Comment by beto-Sibileau** [comment]
hi @lbassil! Yes, these two are different ones. One is related to getting the proper geocodes and the other is related to filtering the dataframe using country names (this is actually now coded with country names and if we do so we need to input country names AS they are returned by the SDMX country codelist (or we should change the code and use ISO3 country codes to filter the dataframe, both would work but will require different changes in the python code)
