### ISSUE TITLE
Add new Gender Cross-Sector Page

### ISSUE THREAD

**Issue by lbassil** [UNICEFECAR/dash#84]
Need to work on the Gender cross-sector page. The page will be title Gender, the buttons will be all the available sectors and the areas under every topic will be the sub-topics of the selected sector.

We should only show disaggregation by Sex (with Total). Keep only sex related indicators.

**Comment by jamescw** [comment]
@lbassil this is done right?

**Comment by lbassil** [comment]
Yes!
